name: Gamedemo
main: org.sobadfish.gamedemo.GameDemoMain
version: 2.3.5
api:
  - 1.0.11
  - 3.0.0
author: sobadfish
load: POSTWORLD
description: "小游戏插件框架"

softdepend:
  - ScoreboardPlugin

loadbefore:
  - ScoreboardPlugin
